version: '3'

services:
  mongo:
    image: mongo:4.4.6
    container_name: tkgtest-api-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: local
    ports:
      - 27018:27017